Add Anomalo <> Datahub Integration DAG
Qbizinc/sandbox-data-pipeline pull request #10
Opened 2024-03-07 18:35 UTC by njfritter

Adding new DAG which pushes Anomalo check results into Qbiz's local Datahub instance.

## Successful DAGRun
![Screenshot 2024-03-07 at 10 34 25 AM](https://github.com/Qbizinc/sandbox-data-pipeline/assets/13670024/170aef4a-c6f8-4008-aaa0-37199a1d338a)

## Datahub Updates
![Screenshot 2024-03-07 at 10 32 59 AM](https://github.com/Qbizinc/sandbox-data-pipeline/assets/13670024/32f8b4fa-3f4f-4795-baac-722c83fa9da6)
![Screenshot 2024-03-07 at 10 33 13 AM](https://github.com/Qbizinc/sandbox-data-pipeline/assets/13670024/f79ae00f-3377-48ec-b027-e2a94673c140)
![Screenshot 2024-03-07 at 10 33 40 AM](https://github.com/Qbizinc/sandbox-data-pipeline/assets/13670024/3c7b38b7-a330-44dc-9617-348d45c14fe3)

2024-03-07 21:33 UTC, AndresAstorgaQbiz approved these changes
LGTM

2024-03-07 22:04 UTC, sorenarchibald approved these changes

2024-03-07 22:12 UTC, AndresAstorgaQbiz requested changes
Added a couple of remarks to the code

2024-03-07 22:12 UTC, AndresAstorgaQbiz commented on dags/anomalo_datahub_integration.py
> +anomalo_instance_host = get_aws_parameter("sandbox_data_pipeline__anomalo_api_host")
Is it possible to include this inside of the functions? I think this will get run by the scheduler

2024-03-07 22:12 UTC, AndresAstorgaQbiz commented on dags/anomalo_datahub_integration.py
> +anomalo_client = anomalo.Client(host=anomalo_instance_host, api_token=anomalo_api_secret_token)
Similarly in this case

2024-03-07 22:19 UTC, sorenarchibald commented on dags/anomalo_datahub_integration.py
> +anomalo_instance_host = get_aws_parameter("sandbox_data_pipeline__anomalo_api_host")
@AndresAstorgaQbiz Are you talking about the global variables?  They wouldn't be globals in a function, no?

2024-03-07 23:19 UTC, njfritter commented on dags/anomalo_datahub_integration.py
> +anomalo_client = anomalo.Client(host=anomalo_instance_host, api_token=anomalo_api_secret_token)
After some looking, I think you're right that the best practice here would be to just have a new API client object get created for each task rather than being created by the scheduler.

Will make these updates.

2024-03-07 23:19 UTC, njfritter commented on dags/anomalo_datahub_integration.py
> +anomalo_instance_host = get_aws_parameter("sandbox_data_pipeline__anomalo_api_host")
@AndresAstorgaQbiz They were originally inside the functions but I moved them outside (to be global variables, as to @sorenarchibald's point) to avoid retrieving the AWS parameters and create an API client multiple times.

I could encapsulate the AWS parameter retrieval into its own task and pass them to the other tasks via XCOMs. Let me look into this.

2024-03-08 00:13 UTC, AndresAstorgaQbiz approved these changes

2024-03-08 18:59 UTC, njfritter commented
DAG Ran successfully last night and results show up in Qbiz's Datahub instance. 

Merging now.

2024-03-08 18:59 UTC, merged