Add task to Sandbox Data Pipeline to Trigger Anomalo Checks on Snowflake Cocktails Staging Table
Qbizinc/sandbox-data-pipeline pull request #30
Opened 2024-04-10 23:08 UTC by njfritter

The Sandbox Data Pipeline was currently missing a task to trigger Anomalo checks on the Snowflake Cocktails staging table because it was not showing up in Qbiz's Anomalo account.

Now that the above issue was solved via #25, that task should be added to the DAG.

2024-04-11 23:56 UTC, sorenarchibald requested changes
`os.env("AIRFLOW_HOME")` Maybe?  see comments

2024-04-11 23:56 UTC, sorenarchibald commented on dags/sandbox_data_pipeline.py
> +sys.path.append("/home/airflow/airflow")
Let's not hardcode this path.  I might want to switch it back to /opt/airflow when we move to ECS.  Is AIRFLOW_HOME the value we want?

2024-04-12 00:22 UTC, njfritter commented on dags/sandbox_data_pipeline.py
> +sys.path.append("/home/airflow/airflow")
Yes you are correct:

<img width="550" alt="Screenshot 2024-04-11 at 5 21 40 PM" src="https://github.com/Qbizinc/sandbox-data-pipeline/assets/13670024/48491f17-0018-47ec-be39-f203fbcde7b8">


I'll go and make that change.

2024-04-12 00:29 UTC, njfritter commented on dags/sandbox_data_pipeline.py
> +sys.path.append("/home/airflow/airflow")
@sorenarchibald Check now when ready

2024-04-12 18:06 UTC, sorenarchibald approved these changes

2024-04-12 21:02 UTC, merged